sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - COPR_REPOSITORY=https://copr.fedorainfracloud.org/coprs/pcon/Solenopsis/
    - OS_ARCH=noarch
  matrix:
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=25
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=26
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=27
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=6

services:
  - docker


install: true

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}

after_success:
  - pip install copr-cli simplejson
  - openssl aes-256-cbc -K $encrypted_56af48627afb_key -iv $encrypted_56af48627afb_iv -in .copr.enc -out .copr -d
  - if [ ! -z "${TRAVIS_TAG}" ]; then copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY} *.src.rpm; fi