sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - COPR_REPOSITORY=Solenopsis
    - OS_ARCH=noarch
    - NAME=solenopsis
    - VERSION=1.2
  matrix:
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7

services:
  - docker

install: true

before_script:
  - mkdir -p /tmp/${NAME}-${VERSION}
  - cp -a * /tmp/${NAME}-${VERSION}/
  - tar czf ${NAME}-${VERSION}.tar.gz -C /tmp ${NAME}-${VERSION}

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}

after_success:
  - pip install copr-cli simplejson jinja2
  - openssl aes-256-cbc -K $encrypted_56af48627afb_key -iv $encrypted_56af48627afb_iv -in .copr.enc -out .copr -d
  - if [ ! -z "${TRAVIS_TAG}" ]; then travis_wait copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY} *.src.rpm; fi